brew "git"
brew "gh"
brew "cocoapods"
brew "zsh"
brew "fdupes"

cask "flutter"
cask "visual-studio-code"
# 自分でAppStoreからインストールする
# cask "xcode"
cask "android-studio"
cask "google-chrome"
cask "slack"
cask "spotify"
cask "zoom"
cask "notion"
cask "figma"
cask "cleanmymac"
